version: "3.9"
networks:
  deploy-guide-dev:
    driver: bridge
services: 
  app:
    container_name: tele-doc
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks: 
      - deploy-guide-dev
    depends_on: 
      - postgres_db
  postgres_db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: tele-doc
    ports:
      - "5432:5432"
    networks: 
      - deploy-guide-dev
    volumes:
      - db-data-volume:/var/lib/postgresql/data
volumes:    
  db-data-volume:  
  